package country;

public enum Region {
    WEST_EUROPE,
    EAST_EUROPE,
    MIDDLEEAST_ASIA,
    SOUTHEAST_ASIA,
    CONTINENTAL_ASIA,
    PACIFIC_OCEAN_ASIA,
    AUSTRALIA_N_OCEANIA,
    LATIN_AMERICA,
    NORTH_AMERICA,
    NORTH_AFRICA,
    CENTRAL_AFRICA,
    SOUTH_AFRICA
}
